#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7
ENV_FILE="$HOME/.sonar/.env"
mkdir -p "$HOME/.sonar"
chmod 700 "$HOME/.sonar"

banner "sonar setup (W0.1): Monid, OpenAI, hackathon, X"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Monid: account and API key"
say "sonar calls Monid over HTTP with a bearer key. Keys are shown once."
open_url "https://app.monid.ai/access/api-keys"
step "Sign up or log in (email or GitHub)."
step "Create an API key named 'sonar'. Copy it now; it will not be shown again."
ask_secret MONID_API_KEY "Paste the Monid API key (starts monid_):"
write_env MONID_API_KEY "$MONID_API_KEY"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Monid: workspace budget and run cap"
say "These are the hard stops behind sonar's own budget guard."
open_url "https://app.monid.ai/rules"
step "Rules: the WORKSPACE_BUDGET control (period DAY) is the daily cap; it ships at 3 USD."
step "Raise it to at least 10 USD. It is workspace-wide: every API key shares it."
step "Per-run cap: sonar enforces MONID_RUN_CAP_USD locally (3.50); Monid has no per-run rule here."
note "Runs past the daily cap return BLOCKED with reason WORKSPACE_BUDGET and an"
note "empty providerResponse (docs/HANDOFF.md, 2026-09-04). Resets 00:00 UTC."
pause "Press Enter once both limits are saved."
write_env MONID_WORKSPACE_BUDGET_USD "10"
write_env MONID_RUN_CAP_USD "3.5"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Monid CLI: install and register the key"
say "The CLI is only used for discover/inspect during development; it is free."
if confirm "Run: npm install -g @monid-ai/cli@latest ?"; then
  npm install -g @monid-ai/cli@latest
fi
if confirm "Register the key with the CLI (monid keys add --label main)?"; then
  monid keys add --label main --key "$MONID_API_KEY"
  monid keys activate --label main || true
  monid whoami || warn "monid whoami failed; check the key"
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "OpenAI: API key"
say "Sentiment, topics and narration run on gpt-5.6-luna with gpt-5.6-terra as tiebreak."
open_url "https://platform.openai.com/api-keys"
step "Create a secret key named 'sonar' with default permissions."
ask_secret OPENAI_API_KEY "Paste the OpenAI key (starts sk-):"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"
if curl -sf -H "Authorization: Bearer $OPENAI_API_KEY" https://api.openai.com/v1/models >/dev/null; then
  say "OpenAI key verified (models list returned)."
else
  warn "OpenAI models list failed; the key may be wrong or lack permissions."
  SKIPPED+=("OpenAI key verification")
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Hackathon registration"
say "Registration is a Google Form linked from the hackathon page."
open_url "https://hacks.monid.ai/"
step "Click the register / submit link and fill the form with the email tied to your Monid account."
step "Use the same X handle you will post from; posts must carry #monid."
pause "Press Enter once the form is submitted."
write_env HACKATHON_REGISTERED_ON "$(date +%F)"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "X account"
say "Reach points need one native-video post on X with #monid in the tweet text."
ask X_HANDLE "X handle you will post from (without @):"
write_env X_HANDLE "$X_HANDLE"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Verify everything"
say "Both checks below are free: discover is unbilled and models.list costs nothing."
if command -v monid >/dev/null 2>&1; then
  monid discover -q "reddit posts" --limit 3 || { warn "monid discover failed"; SKIPPED+=("monid discover check"); }
else
  warn "monid CLI not on PATH"; SKIPPED+=("monid CLI install")
fi
curl -sf -H "Authorization: Bearer $OPENAI_API_KEY" https://api.openai.com/v1/models \
  | grep -o '"id":"gpt-5.6-[a-z]*"' | sort -u || warn "gpt-5.6 ids not visible in models list"
note "Values live in $ENV_FILE (mode 600). sonar reads them via SONAR_ENV or ~/.sonar/.env."
chmod 600 "$ENV_FILE"

finish
